services:
  postgres:
    image: postgres:16
    container_name: dev_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  gymapp:
    image: gymapp:latest  # nome da imagem que você gerou com `docker build -t gymapp .`
    container_name: gymapp
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gymapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SECRET_JWT: supersegredosecreto123
      VARIAVEL_JWT_EXPIRATION: 8100000
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: